### ISSUE TITLE
Firefox doesn't support manifest v3 yet

### ISSUE THREAD

**Issue by remborg** [WebExp0528/React-Extension-Boilerplate#60]
It's not possible to load extensions in Firefox, the browser doesn't support manifest v3 yet.

The error message returned by Firefox when loading the temporary extension is:
```
There was an error during the temporary add-on installation.
Unsupported manifest version: 3
```

--
Also, thank you for sharing this project.

**Comment by Myzel394** [comment]
@remborg Did you find a solution to this?

**Comment by WebExp0528** [comment]
@Myzel394  Do you need a firefox version?

**Comment by Myzel394** [comment]
@WebExp0528 Yes I do need to support Firefox users. Thanks for the superfast answer btw! :sonic:

**Comment by WebExp0528** [comment]
Let me update.

**Comment by WebExp0528** [comment]
@Myzel394  Updated.

**Comment by Myzel394** [comment]
🤯 that was fast, thank you very much!
